const ADJECTIVE_MAP = {
	"A": "Amusing",
	"B": "Brave",
	"C": "Clumsy",
	"D": "Dancing",
	"E": "Enormous",
	"F": "Famous",
	"G": "Great",
	"H": "Helpful",
	"I": "Imaginary",
	"J": "Jolly",
	"K": "Keen",
	"L": "Ludicrous",
	"M": "Mysterious",
	"N": "Nervous",
	"O": "Obnoxious",
	"P": "Pitiful",
	"Q": "Questionable",
	"R": "Rare",
	"S": "Stupendous",
	"T": "Terrible",
	"U": "Unfortunate",
	"V": "Victorious",
	"W": "Weak",
	"X": "Xenophobic",
	"Y": "Yearnful",
	"Z": "Zealous",
} as const

const NOUN_MAP = {
	"A": "Armadillos",
	"B": "Beekeepers",
	"C": "Computers",
	"D": "Desserts",
	"E": "Eagles",
	"F": "Falafels",
	"G": "Giraffes",
	"H": "Hummingbirds",
	"I": "Invertebrates",
	"J": "Jellyfish",
	"K": "Kangaroos",
	"L": "Llamas",
	"M": "Mullets",
	"N": "Novels",
	"O": "Oatmeal",
	"P": "Paragraphs",
	"Q": "Quarterbacks",
	"R": "Rhombuses",
	"S": "Skeletons",
	"T": "Trucks",
	"U": "Unicorns",
	"V": "Vectors",
	"W": "Wombats",
	"X": "Xylophones",
	"Y": "Yachts",
	"Z": "Zebras",
} as const

const VERB_MAP = {
	"A": "Adventuring",
	"B": "Baking",
	"C": "Climbing",
	"D": "Dancing",
	"E": "Eating",
	"F": "Falling",
	"G": "Galloping",
	"H": "Hallucinating",
	"I": "Influencing",
	"J": "Jaywalking",
	"K": "Kayaking",
	"L": "Leading",
	"M": "Maneuvering",
	"N": "Navigating",
	"O": "Organizing",
	"P": "Painting",
	"Q": "Quarrelling",
	"R": "Rambling",
	"S": "Sneezing",
	"T": "Transforming",
	"U": "Unravelling",
	"V": "Vandalizing",
	"W": "Wondering",
	"X": "X-raying",
	"Y": "Yelling",
	"Z": "Zooming",
} as const

const ADVERB_MAP = {
	"A": "Absurdly",
	"B": "Boldly",
	"C": "Carefully",
	"D": "Dauntlessly",
	"E": "Enjoyably",
	"F": "Fervently",
	"G": "Greedily",
	"H": "Hastily",
	"I": "Impeccably",
	"J": "Jokingly",
	"K": "Kindly",
	"L": "Lightly",
	"M": "Majestically",
	"N": "Naturally",
	"O": "Overwhelmingly",
	"P": "Pleasantly",
	"Q": "Quaintly",
	"R": "Rationally",
	"S": "Sanguinely",
	"T": "Tirelessly",
	"U": "Uncontrollably",
	"V": "Vividly",
	"W": "Weirdly",
	"X": "Xerically",
	"Y": "Yieldingly",
	"Z": "Zestfully",
} as const

export type Code = [keyof typeof ADJECTIVE_MAP, keyof typeof NOUN_MAP, keyof typeof VERB_MAP, keyof typeof ADVERB_MAP];

export default function codeToWord(code: Code): string {
	return `${ADJECTIVE_MAP[code[0]]} ${NOUN_MAP[code[1]]} ${VERB_MAP[code[2]]} ${ADVERB_MAP[code[3]]}`;
}